version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    container_name: backend
    ports:
      - '8080:8080'
    command: npm run dev